<form action="/form/index/sendmail" method="post">
    <label for="">
        Your name
        <input type="text" name="name">
    </label><br>
    <label for="">
        Your Email
        <input type="email" name="email">
    </label><br>
    <label for="">
        Your message
        <textarea name="message" id="" cols="30" rows="10" ></textarea>
    </label>
    <input class="btn btn-primary" type="submit">
</form>